//user actions
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const TOGGLE_USER_LOADING = 'TOGGLE_USER_LOADING';

// auth actions
export const SET_ERRORS = "SET_ERRORS";
export const TOGGLE_AUTH_LOADING = "TOGGLE_AUTH_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// organization actions
export const GET_COMPANY = "GET_COMPANY";
export const GET_COMPANY_USERS = "GET_COMPANY_USERS";
export const GET_COMPANY_EXPENSES = "GET_COMPANY_EXPENSES";
export const GET_COMPANY_DEPARTMENTS = "GET_COMPANY_DEPARTMENTS";
export const GET_COMPANY_TOTALS = "GET_COMPANY_TOTALS";
export const GET_COMPANY_PENDING = "GET_COMPANY_PENDING";
export const TOGGLE_COMPANY_LOADING = "TOGGLE_COMPANY_LOADING";

//expense actions
export const TOGGLE_EXPENSE_LOADING = 'TOGGLE_EXPENSE_LOADING';
export const GET_EXPENSE = 'GET_EXPENSE';

//department actions
export const TOGGLE_DEPARTMENT_LOADING = 'TOGGLE_DEPARTMENT_LOADING'
